# ----------- CONFIGURABLE START -----------
title:            "Baruch"
description:      "Such theme, very cool."
#url:              http://scribble.muan.co # Site url, without a slash at the end.
signoff:          "baruch" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

#baseurl: ''
url: 'https://baruch.my.id'


links:
  - name:         Posts
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
